require "plugins/admin"
require "plugins/friendly"
require "plugins/help"
require "plugins/registration_manager"
require "plugins/session_manager"
# require "plugins/tumblrguard"
# require "plugins/tweet"
# require "plugins/twitter_watcher"
# require "plugins/steam"
